### ISSUE TITLE
节点分类和图分类的代码实现

### ISSUE THREAD

**Issue by orangeslx** [ifding/uhgr#1]
你好，这篇论文写得非常好，能否上传一下节点分类和图分类的代码实现，想要学习更多，等待您的回复！

**Comment by ifding** [comment]
Thanks for your attention to our work. All of node classification and graph classification code are included in train.py file (train_node_task and train_graph_task).

**Comment by orangeslx** [comment]
Hello, I would like to ask about the graphics card capacity required for the code to run, approximately, and why such a large capacity is needed.
