### ISSUE TITLE
运行配置问题

### ISSUE THREAD

**Issue by orangeslx** [ifding/uhgr#2]
Hello, I would like to ask about the graphics card capacity required for the code to run, approximately, and why such a large capacity is needed.

**Comment by ifding** [comment]
It depends on the size of your dataset, a very large graph or multiple small graphs. You could set a smaller hidden_dim or output_dim to train the model on your dataset. This model doesn't require too powerful GPU.

**Comment by orangeslx** [comment]
Thank you for your reply. I have a doubt. I use the data set cora given in your paper for training. The capacity of my computer is 6G. I found that the graphics card needs about 14G of capacity. Is this normal? waiting for your reply!


------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "ifding/uhgr"                                                                                    <notifications@github.com&gt;;
发送时间:&nbsp;2020年9月29日(星期二) 中午12:11
收件人:&nbsp;"ifding/uhgr"<uhgr@noreply.github.com&gt;;
抄送:&nbsp;"兜里有颗糖"<1831756224@qq.com&gt;;"Author"<author@noreply.github.com&gt;;
主题:&nbsp;Re: [ifding/uhgr] 运行配置问题 (#2)





 
It depends on the size of your dataset, a very large graph or multiple small graphs. You could set a smaller hidden_dim or output_dim to train the model on your dataset. This model doesn't require too powerful GPU.
